cart/urls.py
from django.urls import path
from .views import add_to_cart, remove_from_cart, view_cart, add_funds, checkout, checkoutRedirect, order_history

app_name = 'cart'

urlpatterns = [
    path('add-to-cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:cart_item_id>/', remove_from_cart, name='remove_from_cart'),
    path('', view_cart, name='view_cart'),
    path('add-funds/', add_funds, name='add_funds'),
    path('checkout/', checkoutRedirect, name='checkout'),
    path('order_complete/', checkout, name='order_complete'),
    path('order-history/', order_history, name='order_history'),
]

my_ecommerce_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('website.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from product.models import Product
from accounts.models import CustomUser
from django.utils import timezone

class CartItem(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    date_added = models.DateField(default=timezone.now, null=False)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=None, null=True)

    def total_price(self):
        if self.price is not None:
            return self.quantity * self.price
        else:
            return 0.0

class Cart(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    items = models.ManyToManyField(CartItem)

    def total_price(self):
        cart_items = self.items.all()
        total_price = sum(item.total_price() for item in cart_items)
        return total_price
    
    def get_total_price(self):
        return '{:.2f}'.format(self.total_price())
    
class Order(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    items = models.ManyToManyField(Product)
    date_ordered = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=8, decimal_places=2, default=0)

    def __str__(self):
        return f"{self.user.username}'s Order ({self.date_ordered.strftime('%b %d, %Y %I:%M %p')})"
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=None, null=True)

    def __str__(self):
        return f"{self.quantity} x {self.product.name}"

    def total_price(self):
        if self.price is not None:
            return self.quantity * self.price
        else:
            return 0.0



    
class Wallet(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)




cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import CartItem, Cart, Wallet, Order, OrderItem
from product.models import Product, Inventory
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.contrib.auth.signals import user_logged_in
from django.dispatch import receiver
from allauth.account.signals import user_signed_up
from decimal import Decimal
from django.contrib import messages
from django.db import transaction

CustomUser = get_user_model()

@login_required
def checkoutRedirect(request):
    # Retrieve the cart for the current user
    cart = Cart.objects.get(user=request.user)
    

    # Check if the cart has items
    if not cart.items.exists():
        return redirect('cart:view_cart')

    # Retrieve the cart items for the current user
    cart_items = CartItem.objects.filter(user=request.user)

    # Calculate the total price of the cart items
    total_price = cart.total_price()

    # Retrieve the user's wallet balance
    wallet = Wallet.objects.get(user=request.user)
    balance = wallet.balance

    # Render the checkout template with the cart items and total price
    return render(request, 'checkout.html', {'cart_items': cart_items, 'total_price': total_price, 'balance': balance})



@transaction.atomic
@login_required
def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    cart_item, created = CartItem.objects.get_or_create(
        product=product,
        user=CustomUser.objects.get(id=request.user.id),
        defaults={'quantity': 1, 'price': product.price},
    )
    if not created:
        cart_item.quantity += 1
        cart_item.save()

    cart, created = Cart.objects.get_or_create(user=CustomUser.objects.get(id=request.user.id))
    cart.items.add(cart_item)

    return redirect('cart:view_cart')

@transaction.atomic
@login_required
def remove_from_cart(request, cart_item_id):
    cart_item = CartItem.objects.get(id=cart_item_id, user=CustomUser.objects.get(id=request.user.id))
    cart_item.delete()
    return redirect('cart:view_cart')

@login_required
def view_cart(request):
    try:
        cart = Cart.objects.get(user=CustomUser.objects.get(id=request.user.id))
        cart_items = cart.items.all()
        if cart_items:
            total_price = cart.get_total_price()
            return render(request, 'cart.html', {'cart_items': cart_items, 'total_price': total_price})
        else:
            message = "There are no items in your cart."
            return render(request, 'emptyCart.html', {'message': message})
    except Cart.DoesNotExist:
        message = "There are no items in your cart."
        return render(request, 'emptyCart.html', {'message': message})
    except AttributeError:
        message = "You need to be logged in to view your cart."
        return render(request, 'emptyCart.html', {'message': message})

@transaction.atomic    
@login_required
def add_funds(request):
    if request.method == 'POST':
        amount = Decimal(request.POST.get('amount'))
        wallet = Wallet.objects.get(user=request.user)
        wallet.balance += amount
        wallet.save()
        return redirect('cart:view_cart')

    return render(request, 'add_funds.html')

@receiver(user_signed_up)
def create_wallet(sender, user, request, **kwargs):
    wallet = Wallet(user=user)
    wallet.save()

@receiver(user_logged_in)
def check_wallet(sender, user, request, **kwargs):
    try:
        wallet = Wallet.objects.get(user=user)
    except Wallet.DoesNotExist:
        wallet = Wallet(user=user)
        wallet.save()

def order_history(request):
    orders = Order.objects.filter(user=request.user)
    return render(request, 'order_history.html', {'orders': orders})

@transaction.atomic
@login_required
def checkout(request):
    # Get the user's cart
    cart = Cart.objects.get(user=request.user)

    # Check if the cart has items
    if not cart.items.exists():
        return redirect('cart:view_cart')
    else:
        # Get the user's wallet
        wallet = Wallet.objects.get(user=request.user)

        # Calculate the cart total and check if the user has sufficient balance
        cart_total = cart.total_price()
        if wallet.balance < cart_total:
            messages.error(request, "Insufficient balance")
            return redirect('cart:add_funds')

        # Create a new order instance
        # Create a list of cart items
        cart_items = cart.items.all()

        # Create a new order instance and set the items field to the list of cart items
        order = Order.objects.create(user=request.user, total_price=cart_total)
        for item in cart_items:
            if item.quantity > item.product.inventory:
                messages.error(request, f"Insufficient inventory for {item.product.name}")
                return redirect('cart:view_cart')
            item.product.inventory -= item.quantity
            item.product.save()
            order_item = OrderItem(order=order, product=item.product, quantity=item.quantity, price=item.price)
            order_item.save()
        

        # Deduct the cart total from the user's balance and clear the user's cart
        wallet.balance -= cart_total
        wallet.save()
        cart_items.delete()
        cart.items.clear()

        messages.success(request, "Order placed successfully")
        return redirect('cart:order_complete')


cart/templates/add_funds.html
{% extends 'master.html' %}

{% block content %}
    <h2>Add Funds</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="amount">Amount:</label>
            <input type="number" name="amount" step="0.01" min="0" max="1000000" required>
            $
        </div>
        <button type="submit">Add Funds</button>
    </form>
{% endblock %}

cart/templates/cart.html
{% extends 'master.html' %}

{% block content %}
  <h1>Your Cart</h1>
  {% if cart_items %}
    <ul>
      {% for item in cart_items %}
        <li>
          {{ item.quantity }} x {{ item.product.name }} - 
          {% if item.price %}
            ${{ item.price }}
          {% else %}
            Price not available
          {% endif %}
          <form method="post" action="{% url 'cart:remove_from_cart' item.id %}">
            {% csrf_token %}
            <button type="submit">Remove</button>
          </form>
        </li>
      {% endfor %}
    </ul>
    <p>Total price: ${{ total_price }}</p>
  {% else %}
    <p>Your cart is empty.</p>
  {% endif %}
{% endblock %}

cart/templates/checkout.html
{% extends 'master.html' %}

{% block content %}
  <h1>Checkout</h1>
  <p>Review your order and complete your purchase:</p>

  <div class="cart-items">
    <table>
      <thead>
        <tr>
          <th>Quantity</th>
          <th>Product</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        {% for item in cart_items %}
        <tr>
          <td>{{ item.quantity }}x</td>
          <td>{{ item.product.name }}</td>
          <td>{{ item.total_price|floatformat:2 }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <p>Total price: ${{ total_price }}</p>
  </div>

  <p>Your wallet balance: {{ balance }}$</p>
  <form method="POST" action="{% url 'cart:order_complete' %}">
    {% csrf_token %}
    <button type="submit">Place order</button>
  </form>
{% endblock %}

cart/templates/emptyCart.html
<!DOCTYPE html>
<html>
    {% extends "master.html" %}

    {% block content %}
    <style>
        body {
          background-image: url('https://shop.millenniumbooksource.com/static/images/cart1.png ');
          background-repeat: no-repeat;
          background-attachment: fixed;
          background-size: 60% 60%;
          background-position: center;
        }
    
    </style>
    
    <a href="/products" style="display: inline-block; background-color: blue; color: white; padding: 10px 20px; text-decoration: none; 
    position: relative; top: 600px; left: 860px;">Continue Shopping!</a>



    {% endblock %}
</html>

cart/templates/order_complete.html
<!DOCTYPE html>
<html>
    {% extends "master.html" %}

    {% block content %}
    <style>
        body {
          background-image: url('https://morethankyounotes.com/wp-content/uploads/2017/02/Customer-Thank-You-Note-1.png ');
          background-repeat: no-repeat;
          background-attachment: fixed;
          background-size: 60% 60%;
          background-position: center;
        }
    
    </style>
    
    <a href="/products" style="display: inline-block; background-color: blue; color: white; padding: 10px 20px; text-decoration: none; 
    position: relative; top: 600px; left: 860px;">Continue Shopping!</a>

    {% endblock %}
</html>

cart/templates/order_history.html
{% extends 'master.html' %}

{% block content %}
    <h1>Order History</h1>
    {% if orders %}
        <ul>
            {% for order in orders %}
                <li>{{ order }} - Total Price: {{ order.total_price }}</li>
                <ul>
                    {% for item in order.orderitem_set.all %}
                        <li>{{ item.quantity }} x {{ item.cart_item.product.name }} - Price: {{ item.price }}</li>
                    {% endfor %}
                </ul>
            {% endfor %}
        </ul>
    {% else %}
        <p>You have no orders.</p>
    {% endif %}
{% endblock %}